name: exercise
on:
    fork
jobs:
    message:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USER_NAME: ${{ github.event.forkee.name }}
        steps:
            - name: Say Thank
              run: echo "🙌 Merci, $USER_NAME 🙌"