name: exercise
on:
    push:
        branches:
            - main
jobs:
    maven:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                distribution: 'oracle' # See 'Supported distributions' for available options
                java-version: '21'
            - run: mvn dependency:resolve
            - run: mvn clean package